version: '3.2'
services:
  boot2dcos-genconf:
    image: boot2dcos/genconf:${DCOS_VERSION}
    build:
      context: .
      args:
        - DCOS_INSTALLER_URL=https://downloads.dcos.io/dcos/stable/${DCOS_VERSION}/dcos_generate_config.sh
        - DOCKER_TGZ_URL=${DOCKER_TGZ_URL:-https://get.docker.com/builds/Linux/x86_64/docker-17.05.0-ce.tgz}
    depends_on: 
      - squid
  squid:
    image: sameersbn/squid:3.3.8-23
    ports:
      - "3128:3128"
    volumes:
      - /srv/docker/squid/cache:/var/spool/squid3